Bilibili:
  room_id: 0

Setting:
  worldName: "world"
  switch: false
  random: true

  # if random is true, use floor and ceil
  floor: 180
  ceil: 300

  # if random is false, use space as later time
  space: 300

Monsters:
  - ENDERMAN
  - CREEPER
  - SPIDER
  - SHULKER
  - ZOMBIE

Animals:
  - PIG
  - SHEEP
  - COW
  - CHICKEN
  - HORSE
  - PANDA
  - RABBIT
  - FOX