Bilibili:
  room_id: 0

Setting:
  worldName: "world"
  switch: true
  random: true

  # if random is true, use floor and ceil
  floor: 0
  celi: 300

  # if random is false, use space as later time
  space: 300