name: DanmakuVote
version: ${project.version}
main: cn.decision01.danmakuvote.DanmakuVote
api-version: 1.13
commands:
  bvote:
    description: DanmakuVote Command
    usage: /bvote <args>
    permission: op
    permission-message: You don`t have <permission> permission.

