name: DanmakuVote
version: ${project.version}
main: cn.decision01.danmakuvote.DanmakuVote
api-version: 1.13
commands:
  setid:
    description: Set your bilibili live id
    usage: /setid [live id]
    permission: op
    permission-message: You don`t have <permission>
  # todo: permission的设置存在权限节点问题，在正式测试之前需要进行修正
  setworld:
    description: Set now world efffected
    usage: /setworld
    permission: op
    permission-message: You don`t have <permission>
  switchvote:
    description: Switch plugin running status
    usage: /switchvote
    permission: op
    permission-message: You don`t have <permission>
  debugvote:
    description: Debug Vote
    usage: /debugvote
    permission: op
    permission-message: You don`t have <permission>
permissions:
